export default function Home() {
  return (
    <main style={{padding:24,fontFamily:'Inter, system-ui, -apple-system, Segoe UI'}}>
      <h1>B&B Manutenção — PWA (demo)</h1>
      <p>App pronto para PWA. Manifesto e service worker configurados.</p>
      <ul>
        <li>Manifest icons use Supabase image render endpoint (correct MIME)</li>
        <li>Service worker will be generated by next-pwa on build</li>
      </ul>
    </main>
  )
}
